using ReportBusiness.ConfigModel;
using System;
using System.Collections.Generic;
using System.Text;

namespace ReportBusiness.ReportSumSpaceUtilization
{
    public class ReportSumSpaceUtilizationViewModel
    {
        public int? rowNum { get; set; }
        public string rowNum_text { get; set; }
        public string locationType_Name { get; set; }
        public LocationTypeViewModel locationTypeList { get; set; }
        public string owner_Name { get; set; }
        public decimal? maxValuePeak { get; set; }
        public int? count_Location { get; set; }
        public string warehouse { get; set; }
        public string report_date_to { get; set; }
        public string report_date { get; set; }
        public Guid? product_Index { get; set; }      
        public string ambientRoom { get; set; }       
        public string date_to { get; set; }
        public string date_from { get; set; }
        public string month { get; set; }
        public int year { get; set; }       
        public decimal? d01 { get; set; }
        public decimal? d02 { get; set; }
        public decimal? d03 { get; set; }
        public decimal? d04 { get; set; }
        public decimal? d05 { get; set; }
        public decimal? d06 { get; set; }
        public decimal? d07 { get; set; }
        public decimal? d08 { get; set; }
        public decimal? d09 { get; set; }
        public decimal? d10 { get; set; }
        public decimal? d11 { get; set; }
        public decimal? d12 { get; set; }
        public decimal? d13 { get; set; }
        public decimal? d14 { get; set; }
        public decimal? d15 { get; set; }
        public decimal? d16 { get; set; }
        public decimal? d17 { get; set; }
        public decimal? d18 { get; set; }
        public decimal? d19 { get; set; }
        public decimal? d20 { get; set; }
        public decimal? d21 { get; set; }
        public decimal? d22 { get; set; }
        public decimal? d23 { get; set; }
        public decimal? d24 { get; set; }
        public decimal? d25 { get; set; }
        public decimal? d26 { get; set; }
        public decimal? d27 { get; set; }
        public decimal? d28 { get; set; }
        public decimal? d29 { get; set; }
        public decimal? d30 { get; set; }
        public decimal? d31 { get; set; }
        public int month_1 { get; set; }

        public decimal? d01_per { get; set; }
        public decimal? d02_per { get; set; }
        public decimal? d03_per { get; set; }
        public decimal? d04_per { get; set; }
        public decimal? d05_per { get; set; }
        public decimal? d06_per { get; set; }
        public decimal? d07_per { get; set; }
        public decimal? d08_per { get; set; }
        public decimal? d09_per { get; set; }
        public decimal? d10_per { get; set; }
        public decimal? d11_per { get; set; }
        public decimal? d12_per { get; set; }
        public decimal? d13_per { get; set; }
        public decimal? d14_per { get; set; }
        public decimal? d15_per { get; set; }
        public decimal? d16_per { get; set; }
        public decimal? d17_per { get; set; }
        public decimal? d18_per { get; set; }
        public decimal? d19_per { get; set; }
        public decimal? d20_per { get; set; }
        public decimal? d21_per { get; set; }
        public decimal? d22_per { get; set; }
        public decimal? d23_per { get; set; }
        public decimal? d24_per { get; set; }
        public decimal? d25_per { get; set; }
        public decimal? d26_per { get; set; }
        public decimal? d27_per { get; set; }
        public decimal? d28_per { get; set; }
        public decimal? d29_per { get; set; }
        public decimal? d30_per { get; set; }
        public decimal? d31_per { get; set; }
        public decimal? maxValuePeak_per { get; set; }
        public int? count_Location_per { get; set; }

        public decimal? d01_sum { get; set; }
        public decimal? d02_sum { get; set; }
        public decimal? d03_sum { get; set; }
        public decimal? d04_sum { get; set; }
        public decimal? d05_sum { get; set; }
        public decimal? d06_sum { get; set; }
        public decimal? d07_sum { get; set; }
        public decimal? d08_sum { get; set; }
        public decimal? d09_sum { get; set; }
        public decimal? d10_sum { get; set; }
        public decimal? d11_sum { get; set; }
        public decimal? d12_sum { get; set; }
        public decimal? d13_sum { get; set; }
        public decimal? d14_sum { get; set; }
        public decimal? d15_sum { get; set; }
        public decimal? d16_sum { get; set; }
        public decimal? d17_sum { get; set; }
        public decimal? d18_sum { get; set; }
        public decimal? d19_sum { get; set; }
        public decimal? d20_sum { get; set; }
        public decimal? d21_sum { get; set; }
        public decimal? d22_sum { get; set; }
        public decimal? d23_sum { get; set; }
        public decimal? d24_sum { get; set; }
        public decimal? d25_sum { get; set; }
        public decimal? d26_sum { get; set; }
        public decimal? d27_sum { get; set; }
        public decimal? d28_sum { get; set; }
        public decimal? d29_sum { get; set; }
        public decimal? d30_sum { get; set; }
        public decimal? d31_sum { get; set; }
        public decimal? maxValuePeak_sum { get; set; }
        public int? count_Location_sum { get; set; }

        public string d01_ { get; set; }
        public string d02_ { get; set; }
        public string d03_ { get; set; }
        public string d04_ { get; set; }
        public string d05_ { get; set; }
        public string d06_ { get; set; }
        public string d07_ { get; set; }
        public string d08_ { get; set; }
        public string d09_ { get; set; }
        public string d10_ { get; set; }
        public string d11_ { get; set; }
        public string d12_ { get; set; }
        public string d13_ { get; set; }
        public string d14_ { get; set; }
        public string d15_ { get; set; }
        public string d16_ { get; set; }
        public string d17_ { get; set; }
        public string d18_ { get; set; }
        public string d19_ { get; set; }
        public string d20_ { get; set; }
        public string d21_ { get; set; }
        public string d22_ { get; set; }
        public string d23_ { get; set; }
        public string d24_ { get; set; }
        public string d25_ { get; set; }
        public string d26_ { get; set; }
        public string d27_ { get; set; }
        public string d28_ { get; set; }
        public string d29_ { get; set; }
        public string d30_ { get; set; }
        public string d31_ { get; set; }
        public string maxValue_ { get; set; }
    }
}
